'use strict';
'require baseclass';

/* One scoped visual system. Argon owns the surrounding page and theme switch. */
var style = `
.cbi-page-actions .cbi-button-apply,.cbi-page-actions .cbi-button-save{background:var(--dark-primary,#4c3e87)!important;border-color:var(--dark-primary,#4c3e87)!important;color:#fff!important;-webkit-text-fill-color:#fff!important}
.cbi-page-actions .cbi-button-reset{background:transparent!important;border:1px solid #8290a6!important;color:inherit!important;-webkit-text-fill-color:currentColor!important}
.agh-ui h2::before,.agh-ui h2::after,.agh-ui h3::before,.agh-ui h3::after{display:none!important;content:none!important}
.agh-ui p{text-indent:0;line-height:1.7}.agh-ui .cbi-value-description{opacity:1!important}
.agh-ui .cbi-tab>a{color:var(--agh-text)!important;background:var(--agh-soft)!important;border-bottom:2px solid var(--agh-primary)}
.agh-ui{display:grid;gap:18px;color:var(--agh-text);--agh-primary:var(--dark-primary,#4c3e87);--agh-text:var(--text-color-high,#283044);--agh-muted:#6c7689;--agh-border:#e3e7ee;--agh-surface:#fff;--agh-soft:#f5f6fa;--agh-input:#fff;--agh-good:#16814b;--agh-bad:#d33250;--agh-warn:#b86a00;--agh-console:#111b2b;--agh-console-fg:#dce7f8;--agh-alert-bg:#fff5e3;--agh-alert-fg:#875611;--agh-status-text:var(--agh-muted);--agh-editor-bg:var(--agh-input);--agh-text-high:var(--agh-text);--agh-text-muted:var(--agh-muted)}
.agh-ui.agh-dark{--agh-text:var(--text-color-high,#e8edf7);--agh-muted:#adb9ce;--agh-border:#334057;--agh-surface:#1b2332;--agh-soft:#151d2b;--agh-input:#111a29;--agh-good:#47d68b;--agh-bad:#ff7c91;--agh-warn:#ffc365;--agh-alert-bg:#352c1d;--agh-alert-fg:#ffd38d}
.agh-ui *{box-sizing:border-box}.agh-ui h2,.agh-ui h3{margin:0;padding:0;background:none;box-shadow:none;border:0;color:var(--agh-text)!important;-webkit-text-fill-color:var(--agh-text)!important;text-shadow:none;font-weight:650;line-height:1.4!important}
.agh-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.agh-heading h2{font-size:26px!important}.agh-heading p{margin:4px 0 0;color:var(--agh-muted);font-size:13px}

.agh-ui .btn,.agh-ui .cbi-button,.agh-ui .agh-soft-btn{display:inline-flex!important;align-items:center;justify-content:center;min-height:42px;padding:9px 16px!important;border:1px solid var(--agh-border)!important;border-radius:22px!important;background:var(--agh-soft)!important;color:var(--agh-text)!important;-webkit-text-fill-color:var(--agh-text)!important;text-decoration:none!important;line-height:1.4;box-shadow:none!important;font-weight:600;white-space:normal;cursor:pointer}
.agh-ui .cbi-button-action,.agh-ui .agh-primary{background:var(--agh-primary)!important;border-color:var(--agh-primary)!important;color:#fff!important;-webkit-text-fill-color:#fff!important}
.agh-ui .cbi-button-negative{background:#d73f5c!important;border-color:#d73f5c!important;color:#fff!important;-webkit-text-fill-color:#fff!important}
.agh-ui .agh-warning{background:#ff9500!important;border-color:#ff9500!important;color:#161d29!important;-webkit-text-fill-color:#161d29!important}
.agh-ui .btn:hover:not([disabled]),.agh-ui .cbi-button:hover:not([disabled]){filter:brightness(1.08)}.agh-ui [disabled]{opacity:.5;cursor:not-allowed}.agh-ui a:focus-visible,.agh-ui button:focus-visible,.agh-ui summary:focus-visible{outline:2px solid var(--agh-primary);outline-offset:3px}
.agh-ui .agh-ok{color:var(--agh-good)!important}.agh-ui .agh-bad{color:var(--agh-bad)!important}.agh-ui .agh-warn{color:var(--agh-warn)!important}.agh-ui .agh-state{font-weight:750!important;border-radius:8px;padding:5px 9px;background:var(--agh-soft)}
.agh-ui .agh-card,.agh-ui .agh-action,.agh-ui .cbi-map{padding:20px;border:1px solid var(--agh-border);border-radius:14px;background:var(--agh-surface);box-shadow:none;color:var(--agh-text);min-width:0}.agh-ui .agh-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.agh-ui .agh-label{font-size:13px;color:var(--agh-muted)}.agh-ui .agh-value{margin-top:10px;font-size:26px;line-height:1.2;font-weight:700;font-variant-numeric:tabular-nums;overflow-wrap:anywhere;color:var(--agh-text)}
.agh-statusbar{display:flex;gap:20px;align-items:center;justify-content:space-between;flex-wrap:wrap;background:var(--agh-surface);border:1px solid var(--agh-border);border-radius:12px;padding:14px 18px}.agh-statusbar>div{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.agh-service-chip strong::before{content:'●';margin-right:7px}.agh-core-chip{color:var(--agh-muted);font-size:13px}
.agh-ui .agh-info{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 28px}.agh-ui .agh-info-row{display:flex;align-items:center;gap:12px;justify-content:space-between;padding:14px 0;border-bottom:1px solid var(--agh-border);min-width:0}.agh-info-row span{color:var(--agh-muted)}.agh-info-row strong{text-align:right;overflow-wrap:anywhere}.agh-section-title{margin-bottom:8px!important;font-size:18px!important}
.agh-ui details.agh-card{padding:0}.agh-ui details>summary{cursor:pointer;padding:16px 20px;color:var(--agh-text);font-weight:650;list-style:revert}.agh-ui .agh-paths{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;padding:0 20px 20px}.agh-ui .agh-path span{display:block;color:var(--agh-muted);font-size:12px}.agh-ui .agh-path code{display:block;background:transparent;color:var(--agh-text);padding:0;margin-top:8px;overflow-wrap:anywhere;white-space:normal}
.agh-ui .agh-alert{padding:14px 18px;border:1px solid var(--agh-border);border-radius:10px;background:var(--agh-alert-bg);color:var(--agh-alert-fg);line-height:1.7;overflow-wrap:anywhere}.agh-ui .agh-alert-compat{margin-top:12px;background:var(--agh-soft);padding:0;color:var(--agh-text);border-radius:10px}.agh-ui .agh-alert-head{display:list-item;padding:12px 16px;cursor:pointer;list-style:revert;color:var(--agh-warn);font-weight:650}.agh-ui .agh-alert-pop{padding:0 16px 16px;line-height:1.7}.agh-ui .agh-alert-copy{margin:0 0 8px;color:var(--agh-muted)}.agh-ui .agh-alert-meta{display:flex;gap:12px;flex-wrap:wrap}.agh-ui .agh-alert-pill{display:flex;gap:8px;font-size:12px}
.agh-ui .agh-action{margin:0 0 14px;padding:18px}.agh-ui .agh-action h3{font-size:17px}.agh-ui .agh-action-head{margin-bottom:8px}.agh-ui .agh-action-badge{display:none}.agh-ui .agh-action p{margin:0 0 14px;color:var(--agh-muted);font-size:13px;line-height:1.7}.agh-ui .agh-row,.agh-ui .agh-button-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.agh-ui .agh-row input,.agh-ui .agh-row select{flex:1;min-width:130px;max-width:100%}.agh-ui .agh-status{padding:12px 14px;margin-top:12px;background:var(--agh-soft);border-radius:8px;font-size:12px;color:var(--agh-muted);line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere}
.agh-ui input[type=text],.agh-ui input[type=password],.agh-ui select,.agh-ui textarea{border:1px solid var(--agh-border)!important;border-radius:9px!important;background:var(--agh-input)!important;color:var(--agh-text)!important;-webkit-text-fill-color:var(--agh-text)!important;text-shadow:none!important;box-shadow:none!important;padding:10px 12px;max-width:100%;min-height:42px}.agh-ui input::placeholder,.agh-ui textarea::placeholder{color:var(--agh-muted)!important}.agh-ui option{background:var(--agh-input);color:var(--agh-text)}.agh-ui .agh-action textarea{width:100%;min-height:160px;margin-top:12px;font:13px/1.6 monospace;resize:vertical}
.agh-ui .cbi-map>h2{display:none}.agh-ui .cbi-map-descr{color:var(--agh-muted);margin:0 0 14px}.agh-ui .cbi-section{border:0;background:transparent;padding:0;margin:0;box-shadow:none}.agh-ui .cbi-section>h3{display:none}.agh-ui .cbi-tabmenu{display:flex;gap:6px;flex-wrap:wrap;padding:0;margin:0 0 18px;border-bottom:1px solid var(--agh-border);background:none;list-style:none}.agh-ui .cbi-tab,.agh-ui .cbi-tab-disabled{background:none;border:0;padding:0;margin:0}.agh-ui .cbi-tab>a,.agh-ui .cbi-tab-disabled>a{padding:10px 12px;display:block;border-radius:8px 8px 0 0;color:var(--agh-muted)!important;text-decoration:none;background:transparent}.agh-ui .cbi-tab-active>a{color:var(--agh-text)!important;background:var(--agh-soft);border-bottom:2px solid var(--agh-primary)}.agh-ui .cbi-tab-descr{color:var(--agh-muted);margin-bottom:16px;font-size:13px;line-height:1.6}
.agh-ui .cbi-value{display:grid;grid-template-columns:minmax(0,1fr);gap:8px;padding:16px 0;border-top:1px solid var(--agh-border);max-width:860px}.agh-ui .cbi-value-title{display:block;width:auto!important;float:none;margin:0;padding:0!important;color:var(--agh-text)!important;font-weight:600}.agh-ui .cbi-value-field{display:block;margin:0!important;padding:0!important;min-width:0}.agh-ui .cbi-value-description{margin-top:7px;color:var(--agh-muted)!important;font-size:12px;line-height:1.6}.agh-ui .cbi-value input:not([type=checkbox]):not([type=radio]),.agh-ui .cbi-value select{width:100%;max-width:580px}.agh-ui .cbi-value .cbi-checkbox{min-height:24px}.agh-ui [data-name^="_agh_"] .cbi-value-field{max-width:none}.agh-ui [data-name^="_agh_"] .cbi-value-title{display:none}.agh-ui .cbi-value[data-name^="_agh_"]{max-width:none;border:0;padding:0}
.agh-ui .agh-toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:14px}.agh-ui .agh-tabs{display:flex;gap:8px;margin-right:auto}.agh-ui .agh-tab{border:0;background:var(--agh-soft);color:var(--agh-muted);padding:10px 14px;border-radius:9px;min-height:42px}.agh-ui .agh-tab.active{color:var(--agh-text);font-weight:700}.agh-ui .agh-console{margin:0;min-height:430px;max-height:65vh;overflow:auto;padding:18px;border-radius:10px;background:var(--agh-console);color:var(--agh-console-fg);font:12px/1.7 monospace;white-space:pre-wrap;overflow-wrap:anywhere}.agh-ui .agh-editor textarea{width:100%;min-height:550px;font:13px/1.6 monospace}.agh-ui .CodeMirror,.agh-ui .CodeMirror-scroll{min-height:550px}.agh-ui .CodeMirror{height:auto}.agh-ui .CodeMirror,.agh-ui .CodeMirror-gutters{background:var(--agh-input);color:var(--agh-text)}.agh-ui .CodeMirror-gutters{border-color:var(--agh-border)}.agh-ui .CodeMirror-linenumber,.agh-ui .cm-comment,.agh-ui .cm-meta{color:var(--agh-muted)}.agh-ui .cm-atom{color:var(--agh-query)}.agh-ui .cm-number{color:var(--agh-ratio)}.agh-ui .cm-string{color:var(--agh-good)}.agh-ui .CodeMirror-cursor{border-left-color:var(--agh-text)}.agh-ui .CodeMirror-selected{background:rgba(110,99,210,.22)}.agh-ui .CodeMirror-gutters{border-radius:8px 0 0 8px}
@media(max-width:720px){.agh-ui{gap:14px}.agh-heading h2{font-size:23px!important}.agh-ui .agh-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.agh-ui .agh-card{padding:16px}.agh-ui .agh-value{font-size:23px}.agh-ui .agh-info,.agh-ui .agh-paths{grid-template-columns:1fr}.agh-ui .cbi-map{padding:14px}.agh-ui .cbi-tabmenu{gap:2px}.agh-ui .cbi-tab>a,.agh-ui .cbi-tab-disabled>a{padding:10px 9px}.agh-ui .agh-heading .btn{padding:9px 12px!important}.agh-ui .agh-console{min-height:350px}}

.agh-ui{width:100%;margin:0;gap:16px;--agh-surface:var(--white,#fff);--agh-soft:#f7f9fb}
.agh-ui.agh-dark{--agh-surface:#232628;--agh-soft:#282d30;--agh-border:#3a4145;--agh-input:#202427;--agh-console:#161a1d;--agh-muted:#b7c0c8}
.agh-heading{padding:8px 0}.agh-ui .agh-card{border-radius:20px;padding:20px}.agh-ui .agh-stats-grid .agh-value{font-size:28px}.agh-ui .agh-statusbar{padding:12px 16px}.agh-ui .agh-core-chip{font-size:12px}

.agh-ui .agh-access .agh-info{background:var(--agh-soft);padding:0 14px;border-radius:8px}.agh-ui .agh-access .agh-info-row:last-child{border:0}.agh-ui .agh-access .agh-info-row>span{display:inline-flex;align-items:center;align-self:center;padding:5px 11px;border:1px solid var(--agh-border);border-radius:999px;background:var(--agh-surface);font-size:12px;line-height:1.5;flex-shrink:0}.agh-ui .agh-bottom-grid{display:grid;grid-template-columns:1.3fr 1fr;gap:16px}.agh-ui .agh-operation{border-radius:12px;padding:8px 10px;display:flex;align-items:center;gap:12px;min-height:48px;border-bottom:1px solid var(--agh-border);color:var(--agh-text)!important;text-decoration:none!important}.agh-operation svg{width:21px;height:21px;flex-shrink:0}.agh-operation .btn{margin-left:auto;font-size:12px;flex-shrink:0;min-height:36px;padding:7px 14px!important}.agh-ui .agh-operation:last-child{border:0}.agh-ui .btn:active{filter:brightness(.94)}.agh-ui .agh-check{display:flex;align-items:center;gap:12px;padding:13px 0;border-bottom:1px solid var(--agh-border)}.agh-check>span:last-child{margin-left:auto;font-size:13px;font-weight:600}.agh-check svg{width:20px;height:20px}.agh-check:last-child{border:0}.agh-ui .agh-stat-note{color:var(--agh-muted);font-size:12px;margin-top:-4px}
.agh-ui{--agh-query:#2463c5;--agh-blocked:#bb3155;--agh-ratio:#7650b9;--agh-latency:#087d86}.agh-ui.agh-dark{--agh-query:#87b8ff;--agh-blocked:#ff94ab;--agh-ratio:#c5a5ff;--agh-latency:#75d5d7}.agh-ui .agh-stat-queries{color:var(--agh-query)}.agh-ui .agh-stat-blocked{color:var(--agh-blocked)}.agh-ui .agh-stat-ratio{color:var(--agh-ratio)}.agh-ui .agh-stat-latency{color:var(--agh-latency)}
.agh-settings .cbi-section{display:grid;grid-template-columns:170px minmax(0,1fr);gap:24px}.agh-settings .cbi-tabmenu{display:flex;flex-direction:column;gap:6px;border:0;border-right:1px solid var(--agh-border);margin:0;padding-right:12px;white-space:normal;overflow:visible}.agh-settings .cbi-tabmenu>li{width:100%;min-height:42px;float:none}.agh-settings .cbi-tabmenu>li>a{display:block;border-radius:8px!important;padding:12px!important;border-bottom:0!important}.agh-settings .cbi-section-node{min-width:0}.agh-settings .cbi-tab-descr{padding:0 0 14px;border-bottom:1px solid var(--agh-border)}.agh-settings .cbi-value{max-width:none;border-top:0;border-bottom:1px solid var(--agh-border);padding:16px 0}.agh-settings .cbi-value:last-child{border-bottom:0}.agh-settings .cbi-map-descr{display:none}
.agh-settings .cbi-checkbox{display:inline-flex;align-items:center;gap:8px}.agh-settings .cbi-checkbox input[type=checkbox]{display:inline-block!important;position:relative!important;opacity:1!important;appearance:none!important;width:42px!important;height:24px!important;min-height:24px!important;padding:0!important;border:0!important;border-radius:20px!important;background:#8d979f!important;cursor:pointer}.agh-settings .cbi-checkbox input[type=checkbox]::before{content:'';position:absolute;width:18px;height:18px;top:3px;left:3px;border-radius:50%;background:#fff;transition:transform .15s}.agh-settings .cbi-checkbox input[type=checkbox]:checked{background:#6366f1!important}.agh-settings .cbi-checkbox input[type=checkbox]:checked::before{transform:translateX(18px)}.agh-settings .cbi-checkbox input[type=checkbox]+label{display:none!important}
.cbi-page-actions{margin:16px 0!important}.agh-ui .agh-settings-detail>summary{padding:12px 0;font-size:14px}.agh-ui .agh-settings-detail .agh-action{margin-top:12px}
.agh-settings [data-tab-title]{background:transparent!important;box-shadow:none!important;border:0!important;padding:0!important;border-radius:0!important}.agh-settings .cbi-value-title{float:none!important;display:block!important;text-align:left!important;width:auto!important;padding:0!important;line-height:1.5!important}.agh-settings .cbi-value-field{display:block!important;line-height:1.5!important}.agh-settings .cbi-value-description{display:block!important;padding:0!important;margin:7px 0 0!important}.agh-settings .cbi-tab-descr{margin:0 0 8px!important;padding:0 0 14px!important}.agh-settings .cbi-value{line-height:1.5!important}.agh-settings input:focus-visible{outline:2px solid var(--agh-primary)!important;outline-offset:3px}
@media(max-width:720px){.agh-ui textarea{min-width:0!important}.cbi-page-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;max-width:100%}.cbi-page-actions .cbi-button{margin:0!important;min-height:44px;white-space:normal}.agh-ui .btn,.agh-ui .cbi-button,.agh-ui .agh-tab{min-height:44px!important}.agh-ui .agh-operation{gap:8px;padding:8px 0}.agh-ui .agh-bottom-grid{grid-template-columns:1fr}.agh-settings .cbi-section{display:block}.agh-settings .cbi-tabmenu{flex-direction:row;flex-wrap:wrap;border-right:0;border-bottom:1px solid var(--agh-border);padding:0 0 12px;margin-bottom:16px}.agh-settings .cbi-tabmenu>li{width:auto}.agh-ui .agh-stats-grid .agh-value{font-size:25px}.agh-ui .agh-access .agh-info{grid-template-columns:1fr}.agh-ui .agh-card{padding:16px}}
`;

function label(english, chinese) {
	var value = _(english);
	var lang = document.documentElement && document.documentElement.lang || '';
	var classes = document.body && document.body.className || '';
	return (/^zh/i.test(lang) || /\blang_zh/i.test(classes)) ? chinese : value;
}

function header() {
	return E('div', { 'class': 'agh-heading' }, [E('div', {}, [E('h2', {}, 'AdGuard Home'), E('p', {}, label('DNS management', 'DNS 管理'))])]);
}


function icon(name) {
 var paths={device:['M4 4h16v12H4z','M8 20h8M12 16v4'],shield:['M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6z','M8 12l3 3 5-6'],log:['M5 3h14v18H5z','M8 7h8M8 11h8M8 15h5'],update:['M20 9a8 8 0 1 0 0 6','M20 3v6h-6'],check:['M4 12l5 5L20 6']};
 var svg=document.createElementNS('http://www.w3.org/2000/svg','svg');
 [['viewBox','0 0 24 24'],['fill','none'],['stroke','currentColor'],['stroke-width','1.6'],['stroke-linecap','round'],['stroke-linejoin','round'],['aria-hidden','true']].forEach(function(a){svg.setAttribute(a[0],a[1]);});
 (paths[name]||paths.device).forEach(function(d){var p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);svg.appendChild(p);});return svg;
}

return baseclass.extend({ style: style, header: header, icon: icon });
